# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceMash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='facemash/photos', verbose_name='Photo')),
                ('ratings', models.FloatField(default=1500, verbose_name='Rating')),
                ('rd', models.FloatField(default=350, verbose_name='Rating Deviation')),
                ('sigma', models.FloatField(default=0.06, verbose_name='Sigma')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'FaceMash',
                'verbose_name_plural': 'FaceMash',
                'ordering': ['-timestamp'],
            },
        ),
    ]
